# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./Frontend
#     ports:
#       - "3000:3000"
#     stdin_open: true
#     tty: true

#   backend:
#     build:
#       context: ./Backend
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: nlpdb
#     ports:
#       - "3306:3306"

version: "3.8"

services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/database_structure.sql:/docker-entrypoint-initdb.d/database_structure.sql

volumes:
  mysql_data:
