version: '3.8'

services:
  frontend:
    build: ./Frontend
    container_name: frontend
    networks:
      - app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    container_name: backend
    networks:
      - app
    ports:
      - "3001:3001"
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: database
    restart: always
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./Backend/demo/:/docker-entrypoint-initdb.d/

networks:
  app:
    driver: bridge
