version: "3.8"

services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://20.3.247.134:3001
    networks:
      - app

  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app
    