apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # Base64 encoded "rootpassword"
  MYSQL_DATABASE: bnlzcw==  # Base64 encoded "mydb"
  MYSQL_USER: dXNlcg==  # Base64 encoded "user"
  MYSQL_PASSWORD: dXNlcnBhc3N3b3Jk  # Base64 encoded "userpassword"
